#!/usr/bin/env node
// Generate the three required secrets for AVM's .env.local in one go.
//
// Usage:
//   node scripts/generate-secrets.mjs            # print to stdout
//   node scripts/generate-secrets.mjs >> .env.local
//
// The script never reads or writes .env.local itself — it only prints.

import { randomBytes } from "node:crypto";

const nextauth = randomBytes(32).toString("base64url");
const encryption = randomBytes(32).toString("hex"); // must be exactly 32 bytes (64 hex)
const pepper = randomBytes(32).toString("base64url");

process.stdout.write(
  [
    "# --- Generated by scripts/generate-secrets.mjs ---",
    `NEXTAUTH_SECRET="${nextauth}"`,
    `IDENTITY_ENCRYPTION_KEY="${encryption}"`,
    `IDENTITY_HASH_PEPPER="${pepper}"`,
    "",
  ].join("\n")
);
